
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "book_management.h"

/*You can extend the structs (Book and BookArray) defined in this head file;
  However, you may not change the function prototypes. 
  You are also free to add additional head files and data structures as needed. 
*/

extern 	struct Book* head_book; 
typedef enum __bool { false = 0, true = 1, } bool;

Book* Insert_book(struct Book *head_book, Book *new_book){
	Book *p, *q;
	p = q = head_book;
	
	if(head_book == NULL){//¿ÕÁ´±í 
		head_book = new_book;
		new_book->next = NULL;
	}
	else{
		while((new_book->id > p->id) && (p->next != NULL)){
			q = p;
			p = p->next;
		}
		if(new_book->id <= p->id){
			new_book->next = p;
			if(head_book == p)
				head_book = new_book;
			else
				q->next = new_book;
		}
		else{
			p->next = new_book;
			new_book->next = NULL;
		}
	}
	return head_book;
};
//saves the database of books in the specified file
//returns 0 if books were stored correctly, or an error code otherwise
int store_books(FILE *file);

int store_books(FILE *file)
{
	
}
//loads the database of books from the specified file
//the file must have been generated by a previous call to store_books()
//returns 0 if books were loaded correctly, or an error code otherwise
int load_books(FILE *file);

//adds a book to the ones available to the library
//returns 0 if the book could be added, or an error code otherwise
int add_book(Book book);

int add_book(Book book)
{
	Book *p_book;
	int id, year, copies, tag;
	char title[20], authors[20];
	int size_book = sizeof(book);
	
	head_book = NULL;
	printf("Please type in the book ID:");
	scanf("%d", &id);
	printf("Please type in the book title:");
	scanf("%s", title);
    printf("Please type in the comma separated list of authors:");
    scanf("%s", authors);
    printf("Please type in the year of publication:");
    scanf("%d", &year);
    printf("Please type in the number of copies:");
    scanf("%d", &copies);
    printf("\n");
    while(true){
    	p_book=(Book *)malloc(size_book);
    	strcpy(p_book->title , title);
    	p_book->id = id;
    	p_book->year = year;
    	p_book->copies = copies;
    	strcpy(p_book->authors, authors);
    	head_book = Insert_book(head_book, p_book);
    	printf("Type in '1' to keep going, or type any key to exit.");
    	scanf("%d, &tag");
    	if(tag != 1){
    		break;
		}
		printf("Please type in the book ID:");
		scanf("%d", &id);
		printf("Please type in the book title:");
		scanf("%s", title);
	    printf("Please type in the comma separated list of authors:");
	    scanf("%s", authors);
	    printf("Please type in the year of publication:");
	    scanf("%d", &year);
	    printf("Please type in the number of copies:");
	    scanf("%d", &copies);
	    printf("\n");
	}
    return 0;
};



//removes a book from the library
//returns 0 if the book could be successfully removed, or an error code otherwise.
int remove_book(Book book);

int remove_book(Book book)
{
	bool flag = true;
	Book *p, *q;
	p = q = head_book;
	
	while(p->id != book.id &&p->next != NULL){
		q = p;
		p = p->next;
	}
	if(p->id == book.id){
		if(p == head_book){
			head_book = p->next;
		}
		
		free(p);
		return 0;
	}
	else{
		flag = false;
		printf("Error: Cannot find this book.");
	}
	
};

//finds books with a given title.
//returns a BookArray structure, where the field "array"
// is a newly allocated array of books, or null if no book with the 
//provided title can be found. The length of the array is also recorded 
//in the returned structure, with 0 in case
//array is the null pointer.
struct BookArray *find_book_by_title (const char *title){
	BookArray *ptr_book;
	ptr_book->array = head_book;
	ptr_book->length = 0;
	while(ptr_book->array != NULL)
	{
		if(strcmp(ptr_book->array->title, title) == 0){
			printf("book ID:", ptr_book->array->id);
			printf("book title:", ptr_book->array->title);
			printf("comma separated list of authors:", ptr_book->array->authors);
			printf("year of publication:", ptr_book->array->year);
			printf("number of copies:", ptr_book->array->copies);
			printf("\n");
			ptr_book->length++;
		}
		if(ptr_book->length > 0)
		{
			break;
		}
		ptr_book->array = ptr_book->array->next;
	}
	if(ptr_book->length == 0){
		printf("Error: There's no such book in the libiary.");
	}
	return ptr_book;
} 


//finds books with the given authors.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the 
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
struct BookArray *find_book_by_author (const char *author){
	Book *found_book, *p_book;
	found_book = head_book;
	BookArray *find_book;
	find_book->array = head_book;
	find_book->length = 0;
	while(p_book != NULL)
	{
		if(strcmp(p_book->authors, author)){
			found_book->id = p_book->id;
			found_book->copies = p_book->copies;
			found_book->year = p_book->year;
			strcpy(found_book->title, p_book->title);
			strcpy(found_book->authors, p_book->authors);
			find_book = Insert_book(find_book->array, found_book);
			find_book->length++;
		}
		p_book = p_book->next;
		
	}
	if(find_book->length == 0){
		printf("Error: There's no such book in the libiary.");
	}
	return find_book;
} 


//finds books published in the given year.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the 
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
struct BookArray *find_book_by_year (unsigned int year){
	Book *found_book, *p_book;
	found_book = head_book;
	BookArray *find_book;
	find_book->array = head_book;
	find_book->length = 0;
	while(p_book != NULL)
	{
		if(p_book->year == year){
			found_book->id = p_book->id;
			found_book->copies = p_book->copies;
			found_book->year = p_book->year;
			strcpy(found_book->title, p_book->title);
			strcpy(found_book->authors, p_book->authors);
			find_book = Insert_book(find_book->array, found_book);
			find_book->length++;
		}
		p_book = p_book->next;
		
	}
	if(find_book->length == 0){
		printf("Error: There's no such book in the libiary.");
	}
	return find_book;
} 



