#ifndef BOOK_MANAGEMENT_GUARD__H 
#define BOOK_MANAGEMENT_GUARD__H

#include <stdio.h>

/*You can extend the structs (Book and BookArray) defined in this head file;
  However, you may not change the function prototypes. 
  You are also free to add additional head files and data structures as needed. 
*/


typedef struct _Book {
	    unsigned int id; //Book ID
		char *title; //book title
		char *authors; //comma separated list of authors
		unsigned int year; // year of publication
		unsigned int copies; //number of copies the library has
}Book;

typedef struct _BookArray {
	 Book* array; // pointer to array (or linked list) of struct Book.
	 unsigned int length; // number of elements in the (Book*) array 
}BookArray;


//saves the database of books in the specified file
//returns 0 if books were stored correctly, or an error code otherwise
int store_books(FILE *file);

int store_books(FILE *file)
{
	
}
//loads the database of books from the specified file
//the file must have been generated by a previous call to store_books()
//returns 0 if books were loaded correctly, or an error code otherwise
int load_books(FILE *file);

//adds a book to the ones available to the library
//returns 0 if the book could be added, or an error code otherwise
int add_book(Book book);

int add_book(Book book)
{
	struct nbook *head_nbook, *p_nbook;
	int id, year, copies, tag;
	char title[20], authors[20];
	int size_nbook = sizeof(struct nbook);
	
	head_nbook = NULL;
	printf("Please type in the book ID:");
	scanf("%d", &id);
	printf("Please type in the book title:");
	scanf("%s", title);
    printf("Please type in the comma separated list of authors:");
    scanf("%s", authors);
    printf("Please type in the year of publication:");
    scanf("%d", &year);
    printf("Please type in the number of copies:");
    scanf("%d", &copies);
    printf("\n");
    while(true){
    	p_nbook=(struct nbook *)malloc(size_nbook);
    	strcpy(p_nbook->book->title, title);
    	p_nbook->book->id = id;
    	p_nbook->book->year = year;
    	p_nbook->book->copies = copies;
    	strcpy(p_nbook->book->authors, authors);
    	head_nbook = Insert_nbook(head_nbook, p_nbook);
    	printf("Type in '1' to keep going, or type any key to exit.");
    	scanf("%d, &tag");
    	if(tag != 1){
    		break;
		}
		printf("Please type in the book ID:");
		scanf("%d", &id);
		printf("Please type in the book title:");
		scanf("%s", title);
	    printf("Please type in the comma separated list of authors:");
	    scanf("%s", authors);
	    printf("Please type in the year of publication:");
	    scanf("%d", &year);
	    printf("Please type in the number of copies:");
	    scanf("%d", &copies);
	    printf("\n");
	}
    return 0;
};

struct nbook *Insert_nbook(struct nbook *head_nbook, struct nbook *new_nbook){
	struct nbook *p, *q;
	p = q = head_nbook;
	
	if(head_nbook == NULL){//¿ÕÁ´±í 
		head_nbook = new_nbook;
		new_nbook->next = NULL;
	}
	else{
		while((new_nbook->book->id > p->book->id) && (p->next != NULL)){
			q = p;
			p = p->next;
		}
		if(new_nbook->book->id <= p->book->id){
			new_nbook->next = p;
			if(head_nbook == p)
				head_nbook = new_nbook;
			else
				q->next = new_nbook;
		}
		else{
			p->next = new_nbook;
			new_nbook->next = NULL;
		}
	}
	return head_nbook;
};

//removes a book from the library
//returns 0 if the book could be successfully removed, or an error code otherwise.
int remove_book(Book book);

int remove_book(Book book)
{
	bool flag = true;
	struct nbook *p, *q;
	p = q = head_nbook;
	
	while(p->book->id != book->id &&p->next != NULL){
		q = p;
		p = p->next;
	}
	if(p->book->id == book->id){
		if(p == head_nbook){
			head_nbook = p->next;
		}
		
		free(p);
		return 0;
	}
	else{
		flag = false;
		printf("Error: Cannot find this book.");
	}
	
};

//finds books with a given title.
//returns a BookArray structure, where the field "array"
// is a newly allocated array of books, or null if no book with the 
//provided title can be found. The length of the array is also recorded 
//in the returned structure, with 0 in case
//array is the null pointer.
BookArray find_book_by_title (const char *title){
	struct BookArray *ptr_nbook = head_book;
	int flag = 0;
	while(ptr_nbook != NULL)
	{
		if(strcmp(ptr_nbook->array->title, title) == 0){
			printf("book ID:", ptr_nbook->array->id);
			printf("book title:", ptr_nbook->array->title);
			printf("comma separated list of authors:", ptr_nbook->array->authors);
			printf("year of publication:", ptr_nbook->array->year);
			printf("number of copies:", ptr_nbook->array->copies);
			printf("\n");
			flag++;
		}
		if(flag > 0)
		{
			break;
		}
		ptr_nbook = ptr_nbook->array//->next;
	}
	if(flag == 0){
		printf("Error: There's no such book in the libiary.");
	}
	return 0;
} 


//finds books with the given authors.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the 
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
BookArray find_book_by_author (const char *author);

//finds books published in the given year.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the 
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
BookArray find_book_by_year (unsigned int year);


#endif
